# Generated by Django 4.1.7 on 2023-07-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
