# Generated by Django 4.1.7 on 2023-07-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='limited',
            field=models.BooleanField(default=False),
        ),
    ]
